### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by edgarrmondragon** [MeltanoLabs/tap-github#307]
```[tasklist]
### Tasks
- [x] Set up trusted publisher on PyPI
- [ ] https://github.com/MeltanoLabs/tap-github/issues/340
- [ ] Use VCS versioning
- [ ] https://github.com/MeltanoLabs/tap-github/issues/341
- [x] Publish: https://pypi.org/project/meltanolabs-tap-github/1.10.0/
- [x] Update MeltanoHub: https://github.com/meltano/hub/pull/1922
```
